# Generated by Django 3.1 on 2020-08-08 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign', '0002_auto_20200808_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tag',
            field=models.CharField(max_length=50, verbose_name='Tag'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('short_desc', models.CharField(max_length=300, verbose_name='Item desc')),
                ('item_cost', models.IntegerField(verbose_name='Item Cost')),
                ('is_funded', models.BooleanField(default=False, verbose_name='Fully Funded?')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
            ],
        ),
    ]
